crud/urls.py
from django.contrib import admin
from django.urls import path , include
from.import views
from crud.views import login 




app_name ="crud"
urlpatterns = [
	path('signup', views.signup ,name = "signup"),
	path('signup/submit', views.submit ,name = "submit"),      
    path('', views.login.as_view() ,),
    path('home',views.useri.as_view(),name = "home"),
    path('home/createtodo',views.createtodo,name = "create"),
    path('logout',views.logout,name="logout"),
    path('home/deletetodo/<int:pk>/',views.deletetodo.as_view(),name = "deletetodo"),
    path('home/updatetodo/<int:pk>/',views.updatetodo.as_view(),name = "updatetodo"),
]	

set/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include ("django.contrib.auth.urls"),),
    path('',include("crud.urls")),
]	

crud/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.







class todo(models.Model):
    checklist= models.CharField(max_length= 1000)
    sprint= models.DateField(blank= True ,null= True)
    user = models.ForeignKey (User,on_delete=models.CASCADE)

    def __str__(self) :
        return f'{ self.user })'

crud/views.py
from django.shortcuts import render
from django.views import View
from django.contrib import auth
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import TemplateView , DetailView , ListView , DeleteView , UpdateView
from django.views.generic import RedirectView
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse, HttpResponseForbidden
from .models import todo
from django.urls import reverse_lazy


#this view is use for submiting signup 
def submit(request):
    if request.method == 'POST':
        
        if request.POST['password1'] == request.POST['password2']: 
            try: 

                user = User.objects.get(username=request.POST['username']) 


                return render(request, 'crud/signup.html', {'error':'Username has already been taken!'})
            except User.DoesNotExist: 

                user = User.objects.create_user(request.POST['username'], request.POST['email'] ,    request.POST['password1'])
                auth.login(request,user)
                return render(request,'crud/dist/index.html', )
                
                
 
        else: # if password 1 and  password2 don't be same :
        	alerts = 'samba' 
        	contex = {'alert' : alerts }
        	return render(request,'templates/crud/signup.html', contex)
    else:
        return redirect('http://127.0.0.1:8000/accounts/login')




#this view is use for create our checklist
def createtodo(request):
	checklistes = request.POST.getlist("checklist")[0]
	sprintes =  request.POST.getlist("sprint")[0]
	apps = todo()
	apps.checklist = checklistes
	apps.sprint = sprintes
	apps.user = request.user
	apps.save()
	return redirect('http://127.0.0.1:8000/home')
		

#in this view client can see lists of his/her checklists
class useri(ListView):
	template_name = 'crud/dist/index.html'
	context_object_name = "todo"
	def get_queryset( self,**kwargs):
		if not self.request.user.is_authenticated:
			return HttpResponseForbidden()
		hold = todo()
		pl = self.request.user
		send = todo.objects.filter(user=pl )
		return send

	#def get_context_data(request,self,**kwargs):
		#context = super().get_context_data(**kwargs)
		#context["todo"] = todo.objects.all()
		#return context
			

#delete check list
class deletetodo(DeleteView):
	model = todo
	success_url = reverse_lazy('crud:home')
	template_name = "crud/delete.html"


#update checklist	
class updatetodo(UpdateView):
	model = todo
	success_url = reverse_lazy('crud:home')
	template_name = "crud/update.html"
	fields = ['checklist','sprint']
	
	




#login
class login(View):
	def dispatch(self , request , *args , **kwargs):
		if request.method == "GET":
			return self.login(request ,  *args , **kwargs )
	def login(self , request):
		follow = True		
		return redirect('http://127.0.0.1:8000/accounts/login/')




#log out
def logout(request):
    return redirect('http://127.0.0.1:8000/accounts/logout/')


# signup
def signup(request):
    return render(request, 'crud/signup.html')
    






# Create your views here.

crud/templates/crud/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <p>ARE YOU REALLY WANT TO DELETE " {{ object }} " </p>
        <input type="submit" value="DELETE">


    </form>
</body>
</html>

crud/templates/crud/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div style="direction: rtl;margin-right: 550px;margin-top: 140px;">     
    <form method="post" action="{% url 'crud:submit' %}">
            {% csrf_token %}
            Username:
            <br>
            <input type="text" name="username" class="form-control"/>
            <br>
            Email:
            <br>
            <input type="email" name="email" class="form-control"/>
            <br>
            Password:
            <br>
            <input type="password" name="password1" class="form-control"/>
            <br>
            Confirm Password:
            <br>
            <input type="password" name="password2" class="form-control"/>
            <br>
            <input class="btn btn-primary" type="submit" value="Sign Up!" class="form-control" style="margin-top: 20px;"/>
            
        </form>
        {% if alert %}
        <script> alert('‍پسورد ها یکسان نیستند'); </script>
        {% endif %}

</div>
</body>
</html>

crud/templates/crud/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="update">


    </form>
</body>
</html>